/*x=5;
console.log(x);
delete x;
console.log(x);

var fruits = ["apple","banana","cherry"];
console.log(fruits.toString());


var fruits = ["apple","banana","cherry","mango"];
console.log(fruits.pop());
console.log(fruits);


var fruits = ["apple","banana","cherry","mango"];
ind=fruits.push("orange");
console.log(fruits);


var fruits = ["apple","banana","cherry","mango"];
var numbers = [1,2,3];
var newArr = fruits.concat(numbers);
console.log(newArr);

var fruits = ["apple","banana","cherry","mango"];
fruits.splice(2,2,"lemon","grapes");
console.log(fruits);
/*
let users = [
    {id: 1, name: "John"},
    {id: 2, name: "Pete"},
    {id: 3, name: "Mary"}
  ];
  
  // returns array of the first two users
  let someUsers = users.filter(item => item.id < 3);
  
  console.log(someUsers.length);*/
  /*var fruits = ["apple","banana","cherry","mango"];
  console.log(fruits.shift());
  console.log(fruits);


  var num = [100,200,300,400,500,600];
  //num[num.length] = 100;
  console.log(num);
  num.slice(4);
  console.log(num);*/
/*
var lengths = ["Bilbo", "Gandalf", "Nazgul"].map(item => item.length)
console.log(lengths);

var num = [23,78,50,2,1];
num.reverse();
console.log(num);
*/
/*
var arr3 = ["Apple","MANGO","KIWI","orange",10,20,"BANANA"];
arr3.sort();
console.log(arr3);

var arr =[2000,250,2,300];
console.log(arr.sort());
arr.sort(function(a,b){
    return a-b;
});
console.log(arr);

var num1 = [100,200,300,400,500];
console.log(num1.slice(2,3));
console.log(num1);*/

var num2 = [100,200,300,400,500];
console.log(num2.includes(400,4));